kind: pipeline
type: docker
name: terraform-infrastructure

environment:
  ### -----------------------
  ### Available in all steps, change app_name to your app_name
  TF_VAR_app_name: tfmultienv
  AWS_REGION: &AWS_REGION eu-west-1
  ### -----------------------
  AWS_DEFAULT_REGION: *AWS_REGION

steps:
  - name: prepare-files-folders
    when:
      branch:
        - dev
        - stg
        - prd
    image: xueshanf/awscli:alpine-3.11
    commands:
      - /bin/bash scripts/prepare-files-folders.sh

  - name: prepare-backend
    depends_on:
      - prepare-files-folders
    when:
      branch:
        - dev
        - stg
        - prd
    image: xueshanf/awscli:alpine-3.11
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id_dev
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key_dev
    commands:
      - /bin/bash scripts/prepare-backend.sh

  - name: terraform-apply
    depends_on:
      - prepare-files-folders
      - prepare-backend
    when:
      branch:
        - dev
        - stg
        - prd
    image: unfor19/drone-terraform:dev
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id_dev
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key_dev
    settings:
      actions:
        - validate
        - plan
        - apply
      root_dir: ${DRONE_BRANCH//\//-}/
      vars:
        environment: ${DRONE_BRANCH//\//-}
